"""api_name is nullable

Revision ID: 0a881891cba4
Revises: 1e5f59ef0521
Create Date: 2024-03-08 14:58:50.577535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a881891cba4'
down_revision = '1e5f59ef0521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product_Retailer', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)

    with op.batch_alter_table('Retailer', schema=None) as batch_op:
        batch_op.drop_constraint('Retailer_api_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Retailer', schema=None) as batch_op:
        batch_op.create_unique_constraint('Retailer_api_name_key', ['api_name'])

    with op.batch_alter_table('Product_Retailer', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
