"""add api_name and improve retailer_location

Revision ID: 1e5f59ef0521
Revises: 843a401898da
Create Date: 2024-03-08 14:47:22.673215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5f59ef0521'
down_revision = '843a401898da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product_Retailer', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)

    with op.batch_alter_table('Retailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_name', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['api_name'])

    with op.batch_alter_table('RetailerLocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RetailerLocation', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('Retailer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_name')

    with op.batch_alter_table('Product_Retailer', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
