"""add image in category

Revision ID: 40cc3e4b4237
Revises: 59de25c0e3ba
Create Date: 2024-03-12 15:27:41.795740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cc3e4b4237'
down_revision = '59de25c0e3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.String(length=1000), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('default_base_increment', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('SubCategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.String(length=1000), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('default_base_increment', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'category_id'),
    sa.UniqueConstraint('api_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('words_tags', sa.String(length=250), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('base_increment', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=2500), nullable=False),
    sa.Column('upc_barcode', sa.String(length=100), nullable=True),
    sa.Column('unit_measure', sa.Enum('ounce', 'pound', 'kilo', 'gram', 'liter', 'gallon', 'milliliter', name='weight'), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('unit_in_pack', sa.Integer(), nullable=True),
    sa.Column('dpci', sa.String(length=30), nullable=True),
    sa.Column('tcin', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.Column('words_tags_tsv', sqlalchemy_utils.types.ts_vector.TSVectorType(), sa.Computed('to_tsvector(\'english\', "words_tags")', persisted=True), nullable=True),
    sa.Column('title_tsv', sqlalchemy_utils.types.ts_vector.TSVectorType(), sa.Computed('to_tsvector(\'english\', "title")', persisted=True), nullable=True),
    sa.Column('brand_tsv', sqlalchemy_utils.types.ts_vector.TSVectorType(), sa.Computed('to_tsvector(\'english\', "brand")', persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['sub_category_id'], ['SubCategory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'sub_category_id'),
    sa.UniqueConstraint('api_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('upc_barcode')
    )
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.create_index('idx_Product_brand_tsv', ['brand_tsv'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_Product_title_tsv', ['title_tsv'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_Product_words_tags_tvs', ['words_tags_tsv'], unique=False, postgresql_using='gin')

    op.create_table('Media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('link_url', sa.String(length=250), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'product_id')
    )
    op.create_table('Product_Retailer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('link_url', sa.String(length=250), nullable=True),
    sa.Column('cost', sa.Float(precision=10), nullable=True),
    sa.Column('increment_retailer', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_in_stock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer_id'], ['Retailer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('link_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Product_Retailer')
    op.drop_table('Media')
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_index('idx_Product_words_tags_tvs', postgresql_using='gin')
        batch_op.drop_index('idx_Product_title_tsv', postgresql_using='gin')
        batch_op.drop_index('idx_Product_brand_tsv', postgresql_using='gin')

    op.drop_table('Product')
    op.drop_table('SubCategory')
    op.drop_table('Category')
    # ### end Alembic commands ###
