"""increase link url from 250 to 350

Revision ID: 4a066d96c2c1
Revises: ca2c34053937
Create Date: 2024-03-18 14:00:30.703840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a066d96c2c1'
down_revision = 'ca2c34053937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.alter_column('link_url',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=350),
               existing_nullable=True)

    with op.batch_alter_table('Product_Retailer', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product_Retailer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('Media', schema=None) as batch_op:
        batch_op.alter_column('link_url',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
