"""description in cat is nullable and not more unique

Revision ID: 59de25c0e3ba
Revises: a1eab5e29e54
Create Date: 2024-03-11 21:00:55.521656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59de25c0e3ba'
down_revision = 'a1eab5e29e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.drop_constraint('Category_description_key', type_='unique')

    with op.batch_alter_table('Product_Retailer', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product_Retailer', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.create_unique_constraint('Category_description_key', ['description'])

    # ### end Alembic commands ###
