version: "3.8"

services:

  auth_gateway:
    container_name: auth_gateway
    init: true
    restart: unless-stopped
    build:
      context: auth_gateway
      dockerfile: Dockerfile-slim-bullseye-python312
    command: tail -F anything
    env_file: auth_gateway/environment_variables/local_dev_auth_gateway.env
    volumes:
      - auth_gateway:/app
    networks:
      - main_net
    depends_on:
      - auth_postgres

  auth_postgres:
    container_name: auth_postgres
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - ~/auth_app/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Pass!123
      - POSTGRES_USER=auth_admin_postgres
      - POSTGRES_DB=authentication
    networks:
      - main_net
