"""create model promotionCoupon

Revision ID: 139c1fd9fa61
Revises: 975df7326f6d
Create Date: 2024-03-06 19:21:51.444451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139c1fd9fa61'
down_revision = '975df7326f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PromotionCoupon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_promotion', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('en', 'es', name='language'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('footer_1', sa.String(length=100), nullable=True),
    sa.Column('footer_2', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_promotion'], ['Promotion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('footer_1'),
    sa.UniqueConstraint('footer_2'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('subtitle'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PromotionCoupon')
    # ### end Alembic commands ###
