"""init

Revision ID: 6462e2185a8f
Revises: 
Create Date: 2024-03-05 20:06:42.108251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6462e2185a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PricingProfile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_profile', sa.String(length=100), nullable=False),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('delivery_fee_base', sa.Float(), nullable=True),
    sa.Column('service_fee_base', sa.Float(), nullable=True),
    sa.Column('minimum_subtotal', sa.Float(), nullable=True),
    sa.Column('rule_access_name', sa.String(length=100), nullable=True),
    sa.Column('level_access_name', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name_profile'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('Promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('value_percent', sa.Float(), nullable=True),
    sa.Column('value_amount', sa.Float(), nullable=True),
    sa.Column('minimum_threshold_subtotal', sa.Float(), nullable=True),
    sa.Column('maximum_threshold_subtotal', sa.Float(), nullable=True),
    sa.Column('minimum_threshold_delivery', sa.Float(), nullable=True),
    sa.Column('maximum_threshold_delivery', sa.Float(), nullable=True),
    sa.Column('minimum_threshold_service', sa.Float(), nullable=True),
    sa.Column('maximum_threshold_service', sa.Float(), nullable=True),
    sa.Column('minimum_threshold_quantity', sa.Integer(), nullable=True),
    sa.Column('type_promotion', sa.Enum('percent', 'amount', name='type_promotion'), nullable=False),
    sa.Column('where_applies', sa.Enum('product', 'product_category', 'product_subcategory', 'product_subtotal', 'delivery_fee', 'service_fee', name='where_applies'), nullable=False),
    sa.Column('times_of_use', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=100), nullable=False),
    sa.Column('rule_access_name', sa.String(length=100), nullable=True),
    sa.Column('level_access_name', sa.String(length=100), nullable=True),
    sa.Column('start_timestamp', sa.Integer(), nullable=False),
    sa.Column('end_timestamp', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_code'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('promotion_name')
    )
    op.create_table('WeightDelivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('delivery_threshold_pound', sa.Float(), nullable=True),
    sa.Column('price_delivery', sa.Float(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('PricingAccount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_account_id', sa.String(length=100), nullable=False),
    sa.Column('pricing_profile_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pricing_profile_id'], ['PricingProfile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_account_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Account_Promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_account_pricing', sa.Integer(), nullable=False),
    sa.Column('id_promotion', sa.Integer(), nullable=False),
    sa.Column('promotions_counter', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_account_pricing'], ['PricingAccount.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_promotion'], ['Promotion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'id_account_pricing', 'id_promotion'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Account_Promotion')
    op.drop_table('PricingAccount')
    op.drop_table('WeightDelivery')
    op.drop_table('Promotion')
    op.drop_table('PricingProfile')
    # ### end Alembic commands ###
