"""update len coupon code

Revision ID: 975df7326f6d
Revises: 4c17af7a281e
Create Date: 2024-03-05 20:31:00.726410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975df7326f6d'
down_revision = '4c17af7a281e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Promotion', schema=None) as batch_op:
        batch_op.alter_column('coupon_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Promotion', schema=None) as batch_op:
        batch_op.alter_column('coupon_code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
