"""add fields size in model promotionCoupon

Revision ID: ed596099cc28
Revises: 139c1fd9fa61
Create Date: 2024-03-06 19:34:38.319771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed596099cc28'
down_revision = '139c1fd9fa61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PromotionCoupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_font_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sub_title_font_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description_font_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('footer_1_font_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('footer_2_font_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('image_width', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PromotionCoupon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_width')
        batch_op.drop_column('footer_2_font_size')
        batch_op.drop_column('footer_1_font_size')
        batch_op.drop_column('description_font_size')
        batch_op.drop_column('sub_title_font_size')
        batch_op.drop_column('title_font_size')

    # ### end Alembic commands ###
