 FROM python:3.12.0-slim-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y git
RUN apt-get install build-essential -y
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install watchdog
